---

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, _drafts]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Slides, Talks and Workshops | Thomas Lohner | SysEleven"
keywords:    "Thomas Lohner, Slides, Presentations, Workshops"
description: "This is a collection of my Talks, Slides and Workshops"
source_link: "https://ThomasLohner.github.io/slides"
#favicon:     "img/favicon.ico"
#touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-3595616-6


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
